name: NEORV32 RISCOF Verification

on:
  push:
  workflow_dispatch:

jobs:

  verify:
    runs-on: ubuntu-latest

    steps:

    - name: '📂 Repository Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install RISC-V GCC'
      run: |
        wget -q https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
        mkdir $GITHUB_WORKSPACE/riscv-gcc
        tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz -C $GITHUB_WORKSPACE/riscv-gcc
        echo $GITHUB_WORKSPACE/riscv-gcc/bin >> $GITHUB_PATH

    - name: '📦 Install sail-riscv model'
      run: |
        mkdir $GITHUB_WORKSPACE/sail-riscv
        tar -xzf $GITHUB_WORKSPACE/bin/sail-riscv.18.09.22.tar.gz -C $GITHUB_WORKSPACE/sail-riscv
        echo $GITHUB_WORKSPACE/sail-riscv >> $GITHUB_PATH

    - name: '📦 Install RISCOF'
      run: pip3 install git+https://github.com/riscv/riscof.git

    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl-ci@nightly

#   - name: '🔄 Applying riscv-arch-test patch'
#     run: |
#       echo "Patching riscv-arch-test..."
#       cat riscv-arch-test.mtval_ebreak.patch
#       patch -u riscv-arch-test/riscv-test-suite/env/arch_test.h -i riscv-arch-test.mtval_ebreak.patch

    - name: '✔️ Check Tools'
      run: |
        riscv32-unknown-elf-gcc -v
        riscv_sim_RV32 -h
        riscof --version
        ghdl -v

    - name: '⚙️ Run verification framework'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/run.sh && $GITHUB_WORKSPACE/run.sh"

    - name: '📤 Archive test report'
      uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: |
          riscof_work/report.html
          riscof_work/style.css
